spring.application.name=beloved-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/beloved
spring.datasource.username=postgres
spring.datasource.password=geldigene06.
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
